name: Build a docker image
description: |
  Build a docker image.
  v2 is available for using multiple tags and building from an private registry image.

inputs:
  dockerfile:
    description: The Dockerfile to build.
    required: false
    default: Dockerfile

  context:
    description: The build context to use.
    required: false
    default: .

  tag:
    description: |
      The tag to use for the image.

      Required for dockerfile building.
      From v2 on you can use multiple tags with 'tags'.
    required: false
    default: docker-image:latest

  composefile:
    description: "The docker-compose file to build. Providing this input will ignore: dockerfile, context, tag"
    required: false

branding:
  icon: "gift"
  color: "blue"

runs:
  using: "node12"
  main: "dist/index.js"
