name: Build a docker image
description: Build a docker image

inputs:
  dockerfile:
    description: The Dockerfile to build.
    required: false
    default: Dockerfile

  composefile:
    description: "The docker-compose file to build. Providing this input will ignore: dockerfile, context, tag"
    required: false

  context:
    description: The build context to use.
    required: false
    default: .

  tag:
    description: |
      The tag to use for the image.

      Required for dockerfile building.
      In @v2 you can use 'tags' to set multiple tags.
    required: false
    default: docker-image:latest

  tags:
    description: |
      From @v2 on. If you want to use multiple tags for the image.

      Required for dockerfile building.
    required: false

  registry:
    description: "The private registry that is referenced in a Dockerfile or docker-compose.yml. Required with `username` and `password`."
    required: false

  username:
    description: "The login username for the private registry. Required with `registry` and `password`."
    required: false

  password:
    description: "The login password for the private registry. Required with `registry` and `username`."
    required: false

branding:
  icon: "gift"
  color: "blue"

runs:
  using: "node12"
  main: "dist/index.js"
