// This file was autogenerated.

    import core from "@actions/core";
    
    export interface InputParameters {
        /**
         * The Dockerfile to build.
         */
        dockerfile: string;
        /**
         * The build context to use.
         */
        context: string;
        /**
         * The docker-compose file to build. Providing this input will ignore: dockerfile, context
         */
        composefile?: string;
    }
    
    export function getInputParameters(): InputParameters {
        return {
            dockerfile: core.getInput("dockerfile", { required: false }) || "Dockerfile",
            context: core.getInput("context", { required: false }) || ".",
            composefile: core.getInput("composefile", { required: false }) || undefined,
        };
    }
    